- name: set brave nightly apt gpg key
  become: yes
  apt_key:
    url: "https://brave-browser-apt-nightly.s3.brave.com/brave-core-nightly.asc"
    state: present

- name: add brave nightly repository
  become: yes
  template:
      src: brave-browser-nightly.list.j2
      dest: /etc/apt/sources.list.d/brave-browser-nightly.list
      group: root
      owner: root
      mode: '0644'

- name: install brave nightly
  become: yes
  apt:
    name: brave-browser-nightly
    update_cache: true